apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord-ui-showcase
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - runtime-secret.yaml
  - deployment.yaml
