apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: discord-ui-showcase-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: discord-ui-showcase
  mount: kv
  type: kv-v2
  path: apps/discord-ui-showcase/prod/runtime
  refreshAfter: 30s
  destination:
    name: discord-ui-showcase-runtime
    create: true
    overwrite: true
