apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: discord-ui-showcase
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: discord-ui-showcase
    serviceAccount: discord-ui-showcase
